export const DBINTERCEPTOR_API = 'https://dbinterceptor-f.herokuapp.com'
// export const MADOFXORD_API = 'https://oxford-transformer.herokuapp.com'
// export const DBINTERCEPTOR_API = 'http://localhost:4000'
export const MADOFXORD_API = 'https://oxfordapif.herokuapp.com'
export const MAILID = 'missionadmission.world@gmail.com'
